title: Below The Terrace
author:
  name: vel
description: My beautiful Github
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - title: Check out my github
      icon: github
      url: "https://github.com/Velocitynotvs"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
