title: Below The Terrace
author: https://github.com/Velocitynotvs/Velocitynotvs.github.io
description: Ma beutitful Github
remote_theme: jekyll/minima
minima:
  skin: dark
  plugins:
  - jekyll-feed
  - jekyll-remote-theme
